name: Check Pull Request

on:
  workflow_dispatch:
    inputs:
      target_service:
        description: 'Input a service name (e.g., demo-app)'
        required: true
      target_version:
        description: 'Input a version (e.g., v1.0.0)'
        required: true

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow in Another Repository
        run: |
          # Set the required variables
          repo_owner="kdivya153" 
          repo_name="REPO2"  
          event_type="trigger-workflow" 
          service=${{ github.event.inputs.target_service }}"
          version="${{ github.event.inputs.target_version }}"

          curl -X POST https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
          -H 'Accept: application/vnd.github.everest-preview+json' \
          -u ${{ secrets.PR_KEY }} \
           -d '{\"event_type\": \"$event_type\", \"client_payload\": {\"service\": \"$service\", \"version\": \"$version\", \"unit\": false, \"integration\": true}}'
          
          
            
           
